### ISSUE TITLE
Add 'disapprovals'

### ISSUE THREAD

**Issue by nicolasbock** [lgtmco/lgtm#49]
# Use Scenario

A reviewer is unhappy with the current state of the PR. They express they disapproval with a `-1`.
# New Behavior

The `lgtm` approver counts all approvals as `+1` and all disapprovals as `-1`, tallies them up, and only if their sum is greater than a configurable threshold is the PR approved.
# Requirements

Configurable set of regexpressions for recognized disapprovals.

**Comment by bradrydzewski** [comment]
just wanted to note that we should probably make the disapproval pattern configurable:

``` diff
approvals = 1
pattern = "(?i)LGTM"
+disapprovals = "(?i):\\-1:"
```

**Comment by nicolasbock** [comment]
The option naming is inconsistent at this point (`approvals` means something completely different than `disapprovals`). A more consistent approach would be:

```
approval_threshold = 2
approval_pattern = "(?i)LGTM"
disapproval_pattern = "(?i):\\-1:"
```

**Comment by tboerger** [comment]
Naming it `approval_pattern` and `disapproval_pattern` makes sense for me, but than we need to fallback to the old behavior to avoid breaking installs.

**Comment by ljharb** [comment]
Probably `disapproval_threshold` would make sense too? That way people could set it to `0` to disable, or `2` to require 2 -1s before something's blocked, etc

**Comment by bradrydzewski** [comment]
> The option naming is inconsistent at this point (approvals means something completely different than disapprovals). A more consistent approach would be:

while I agree, unfortunately this would be a breaking change for projects using hosted [lgtm.co](https://lgtm.co). I would probably prefer a non-uniform solution for the initial implementation, and we can address naming consistency / file format changes in a separate pull request.

> Probably disapproval_threshold would make sense too? That way people could set it to 0 to disable, or 2 to require 2 -1s before something's blocked, etc

@ljharb I hadn't thought of this, but seems to make sense. If too many people dislike the pull request drone refuses to unlock it. This should probably be an optional feature. In fact, disapprovals in general should probably be opt-in since I could see people not expecting that behavior and opening issues telling me everything is broken :)

**Comment by ljharb** [comment]
Right - `disapproval_threshold` would default to `0` which means it can't be disapproved.

**Comment by ljharb** [comment]
Also you could totally do `approval_threshold || approvals` and `approval_pattern || pattern` for now to make it semver-minor, and in the next semver-major, drop the `||` fallbacks.

**Comment by bradrydzewski** [comment]
@ljharb we can definitely update the naming conventions and map the old file values. If we adjust the file properties we could also consider nesting. The file (with all options) would then look something like this:

``` toml
[approval]
threshold = 2
pattern = "(?i)LGTM"
disable_self = true

[disapproval]
enabled = true # if false, won't look for the disapproval pattern
threshold = 2 # if exceeded the pr cannot be unlocked by lgtm. if zero, the pr can be unlocked if lgtm approvals - disapprovals > threshold
pattern = "(?i):\\-1:"
disable_self = true

[maintainers]
path = "MAINTAINERS" # customize file path for teams that place in .github/MAINTAINERS
team = "maintainers" # customize team name container approver list
```
